development:
  host: localhost
  database: driver_services_api_development

test:
  host: localhost
  database: driver_services_api_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>